apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-extractor
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: sample-extractor
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: sample-extractor
    spec:
      containers:
      - name: sample-extractor
        image: t2c2/sample-extractor
        env:
        - name: "RABBITMQ_URL"
          value: "amqp://guest:guest@192.168.3.153:5672/%2f"
        - name: "RABBITMQ_EXCHANGE"
          value: "clowder"
        - name: "MESSAGE_TYPE"
          value: "*.file.image.#"
        - name: "SSL_VERIFY"
          value: "False"

